/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wl_www_FreezeJson8Holder */

#ifndef _Included_com_wl_www_FreezeJson8Holder
#define _Included_com_wl_www_FreezeJson8Holder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wl_www_FreezeJson8Holder
 * Method:    _Init
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_wl_www_FreezeJson8Holder__1Init__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_wl_www_FreezeJson8Holder
 * Method:    _Init
 * Signature: (Lcom/wl/www/FreezeJson4Holder;I)J
 */
JNIEXPORT jlong JNICALL Java_com_wl_www_FreezeJson8Holder__1Init__Lcom_wl_www_FreezeJson4Holder_2I
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     com_wl_www_FreezeJson8Holder
 * Method:    _Free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_wl_www_FreezeJson8Holder__1Free
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_wl_www_FreezeJson8Holder
 * Method:    _writeObject
 * Signature: (JLjava/io/ObjectOutputStream;)V
 */
JNIEXPORT void JNICALL Java_com_wl_www_FreezeJson8Holder__1writeObject
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     com_wl_www_FreezeJson8Holder
 * Method:    _readObject
 * Signature: (Ljava/io/ObjectInputStream;)J
 */
JNIEXPORT jlong JNICALL Java_com_wl_www_FreezeJson8Holder__1readObject
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wl_www_FreezeJson8Holder
 * Method:    _BodySize
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_wl_www_FreezeJson8Holder__1BodySize
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
