/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wl_www_RapidJson */

#ifndef _Included_com_wl_www_RapidJson
#define _Included_com_wl_www_RapidJson
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wl_www_RapidJson
 * Method:    _IsNull
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_wl_www_RapidJson__1IsNull
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_wl_www_RapidJson
 * Method:    _IsFalse
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_wl_www_RapidJson__1IsFalse
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_wl_www_RapidJson
 * Method:    _IsTrue
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_wl_www_RapidJson__1IsTrue
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_wl_www_RapidJson
 * Method:    _IsInt
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_wl_www_RapidJson__1IsInt
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_wl_www_RapidJson
 * Method:    _IsUint
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_wl_www_RapidJson__1IsUint
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_wl_www_RapidJson
 * Method:    _IsDouble
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_wl_www_RapidJson__1IsDouble
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_wl_www_RapidJson
 * Method:    _IsString
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_wl_www_RapidJson__1IsString
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_wl_www_RapidJson
 * Method:    _IsArray
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_wl_www_RapidJson__1IsArray
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_wl_www_RapidJson
 * Method:    _IsObject
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_wl_www_RapidJson__1IsObject
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_wl_www_RapidJson
 * Method:    _GetType
 * Signature: (J)C
 */
JNIEXPORT jchar JNICALL Java_com_wl_www_RapidJson__1GetType
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_wl_www_RapidJson
 * Method:    _GetInt
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_wl_www_RapidJson__1GetInt
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_wl_www_RapidJson
 * Method:    _GetUint
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_wl_www_RapidJson__1GetUint
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_wl_www_RapidJson
 * Method:    _GetDouble
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_com_wl_www_RapidJson__1GetDouble
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_wl_www_RapidJson
 * Method:    _GetString
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_wl_www_RapidJson__1GetString
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_wl_www_RapidJson
 * Method:    _GetArraySize
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_wl_www_RapidJson__1GetArraySize
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_wl_www_RapidJson
 * Method:    _GetArray
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_com_wl_www_RapidJson__1GetArray
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_wl_www_RapidJson
 * Method:    _GetObjectSize
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_wl_www_RapidJson__1GetObjectSize
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_wl_www_RapidJson
 * Method:    _GetObjectKey
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_wl_www_RapidJson__1GetObjectKey
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_wl_www_RapidJson
 * Method:    _GetObject
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_com_wl_www_RapidJson__1GetObject
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_wl_www_RapidJson
 * Method:    _SearchObject
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_wl_www_RapidJson__1SearchObject
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_wl_www_RapidJson
 * Method:    _Locate
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_wl_www_RapidJson__1Locate
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_wl_www_RapidJson
 * Method:    _InitNull
 * Signature: (Lcom/wl/www/RapidDocument;)J
 */
JNIEXPORT jlong JNICALL Java_com_wl_www_RapidJson__1InitNull
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wl_www_RapidJson
 * Method:    _InitFalse
 * Signature: (Lcom/wl/www/RapidDocument;)J
 */
JNIEXPORT jlong JNICALL Java_com_wl_www_RapidJson__1InitFalse
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wl_www_RapidJson
 * Method:    _InitTrue
 * Signature: (Lcom/wl/www/RapidDocument;)J
 */
JNIEXPORT jlong JNICALL Java_com_wl_www_RapidJson__1InitTrue
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wl_www_RapidJson
 * Method:    _InitInt
 * Signature: (JLcom/wl/www/RapidDocument;)J
 */
JNIEXPORT jlong JNICALL Java_com_wl_www_RapidJson__1InitInt
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     com_wl_www_RapidJson
 * Method:    _InitUint
 * Signature: (JLcom/wl/www/RapidDocument;)J
 */
JNIEXPORT jlong JNICALL Java_com_wl_www_RapidJson__1InitUint
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     com_wl_www_RapidJson
 * Method:    _InitDouble
 * Signature: (DLcom/wl/www/RapidDocument;)J
 */
JNIEXPORT jlong JNICALL Java_com_wl_www_RapidJson__1InitDouble
  (JNIEnv *, jobject, jdouble, jobject);

/*
 * Class:     com_wl_www_RapidJson
 * Method:    _InitString
 * Signature: (Ljava/lang/String;Lcom/wl/www/RapidDocument;)J
 */
JNIEXPORT jlong JNICALL Java_com_wl_www_RapidJson__1InitString
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     com_wl_www_RapidJson
 * Method:    _InitArray
 * Signature: (Lcom/wl/www/RapidDocument;)J
 */
JNIEXPORT jlong JNICALL Java_com_wl_www_RapidJson__1InitArray
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wl_www_RapidJson
 * Method:    _InitObject
 * Signature: (Lcom/wl/www/RapidDocument;)J
 */
JNIEXPORT jlong JNICALL Java_com_wl_www_RapidJson__1InitObject
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wl_www_RapidJson
 * Method:    _Freeze4
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_wl_www_RapidJson__1Freeze4
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_wl_www_RapidJson
 * Method:    _Freeze8
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_wl_www_RapidJson__1Freeze8
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_wl_www_RapidJson
 * Method:    _SetNull
 * Signature: (JLcom/wl/www/RapidDocument;)V
 */
JNIEXPORT void JNICALL Java_com_wl_www_RapidJson__1SetNull
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     com_wl_www_RapidJson
 * Method:    _SetFalse
 * Signature: (JLcom/wl/www/RapidDocument;)V
 */
JNIEXPORT void JNICALL Java_com_wl_www_RapidJson__1SetFalse
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     com_wl_www_RapidJson
 * Method:    _SetTrue
 * Signature: (JLcom/wl/www/RapidDocument;)V
 */
JNIEXPORT void JNICALL Java_com_wl_www_RapidJson__1SetTrue
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     com_wl_www_RapidJson
 * Method:    _SetInt
 * Signature: (JJLcom/wl/www/RapidDocument;)V
 */
JNIEXPORT void JNICALL Java_com_wl_www_RapidJson__1SetInt
  (JNIEnv *, jobject, jlong, jlong, jobject);

/*
 * Class:     com_wl_www_RapidJson
 * Method:    _SetUint
 * Signature: (JJLcom/wl/www/RapidDocument;)V
 */
JNIEXPORT void JNICALL Java_com_wl_www_RapidJson__1SetUint
  (JNIEnv *, jobject, jlong, jlong, jobject);

/*
 * Class:     com_wl_www_RapidJson
 * Method:    _SetDouble
 * Signature: (JDLcom/wl/www/RapidDocument;)V
 */
JNIEXPORT void JNICALL Java_com_wl_www_RapidJson__1SetDouble
  (JNIEnv *, jobject, jlong, jdouble, jobject);

/*
 * Class:     com_wl_www_RapidJson
 * Method:    _SetString
 * Signature: (JLjava/lang/String;Lcom/wl/www/RapidDocument;)V
 */
JNIEXPORT void JNICALL Java_com_wl_www_RapidJson__1SetString
  (JNIEnv *, jobject, jlong, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
