/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wl_www_FreezeDocument */

#ifndef _Included_com_wl_www_FreezeDocument
#define _Included_com_wl_www_FreezeDocument
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wl_www_FreezeDocument
 * Method:    _Init
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_wl_www_FreezeDocument__1Init__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_wl_www_FreezeDocument
 * Method:    _Init
 * Signature: (Lcom/wl/www/FreezeDocument;I)J
 */
JNIEXPORT jlong JNICALL Java_com_wl_www_FreezeDocument__1Init__Lcom_wl_www_FreezeDocument_2I
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     com_wl_www_FreezeDocument
 * Method:    _Free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_wl_www_FreezeDocument__1Free
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_wl_www_FreezeDocument
 * Method:    _BodySize
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_wl_www_FreezeDocument__1BodySize
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_wl_www_FreezeDocument
 * Method:    _IsNull
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_com_wl_www_FreezeDocument__1IsNull
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_wl_www_FreezeDocument
 * Method:    _IsFalse
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_com_wl_www_FreezeDocument__1IsFalse
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_wl_www_FreezeDocument
 * Method:    _IsTrue
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_com_wl_www_FreezeDocument__1IsTrue
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_wl_www_FreezeDocument
 * Method:    _IsInt
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_com_wl_www_FreezeDocument__1IsInt
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_wl_www_FreezeDocument
 * Method:    _IsUint
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_com_wl_www_FreezeDocument__1IsUint
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_wl_www_FreezeDocument
 * Method:    _IsDouble
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_com_wl_www_FreezeDocument__1IsDouble
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_wl_www_FreezeDocument
 * Method:    _IsString
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_com_wl_www_FreezeDocument__1IsString
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_wl_www_FreezeDocument
 * Method:    _IsArray
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_com_wl_www_FreezeDocument__1IsArray
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_wl_www_FreezeDocument
 * Method:    _IsObject
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_com_wl_www_FreezeDocument__1IsObject
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_wl_www_FreezeDocument
 * Method:    _GetType
 * Signature: (JI)C
 */
JNIEXPORT jchar JNICALL Java_com_wl_www_FreezeDocument__1GetType
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_wl_www_FreezeDocument
 * Method:    _GetInt
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_com_wl_www_FreezeDocument__1GetInt
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_wl_www_FreezeDocument
 * Method:    _GetUint
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_com_wl_www_FreezeDocument__1GetUint
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_wl_www_FreezeDocument
 * Method:    _GetDouble
 * Signature: (JI)D
 */
JNIEXPORT jdouble JNICALL Java_com_wl_www_FreezeDocument__1GetDouble
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_wl_www_FreezeDocument
 * Method:    _GetString
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_wl_www_FreezeDocument__1GetString
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_wl_www_FreezeDocument
 * Method:    _GetArraySize
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_wl_www_FreezeDocument__1GetArraySize
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_wl_www_FreezeDocument
 * Method:    _GetArray
 * Signature: (JII)I
 */
JNIEXPORT jint JNICALL Java_com_wl_www_FreezeDocument__1GetArray
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     com_wl_www_FreezeDocument
 * Method:    _GetObjectSize
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_wl_www_FreezeDocument__1GetObjectSize
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_wl_www_FreezeDocument
 * Method:    _GetObjectKey
 * Signature: (JII)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_wl_www_FreezeDocument__1GetObjectKey
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     com_wl_www_FreezeDocument
 * Method:    _GetObject
 * Signature: (JII)I
 */
JNIEXPORT jint JNICALL Java_com_wl_www_FreezeDocument__1GetObject
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     com_wl_www_FreezeDocument
 * Method:    _SearchObject
 * Signature: (JILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_wl_www_FreezeDocument__1SearchObject
  (JNIEnv *, jobject, jlong, jint, jstring);

/*
 * Class:     com_wl_www_FreezeDocument
 * Method:    _Locate
 * Signature: (JILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_wl_www_FreezeDocument__1Locate
  (JNIEnv *, jobject, jlong, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
