/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wl_www_RapidDocument */

#ifndef _Included_com_wl_www_RapidDocument
#define _Included_com_wl_www_RapidDocument
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wl_www_RapidDocument
 * Method:    _Init
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_wl_www_RapidDocument__1Init
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_wl_www_RapidDocument
 * Method:    _Free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_wl_www_RapidDocument__1Free
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_wl_www_RapidDocument
 * Method:    _GetAllocator
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_wl_www_RapidDocument__1GetAllocator
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
