/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wl_www_RapidDocument */

#ifndef _Included_com_wl_www_RapidDocument
#define _Included_com_wl_www_RapidDocument
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wl_www_RapidDocument
 * Method:    _Init
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_wl_www_RapidDocument__1Init
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_wl_www_RapidDocument
 * Method:    _Free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_wl_www_RapidDocument__1Free
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_wl_www_RapidDocument
 * Method:    _Freeze4
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_com_wl_www_RapidDocument__1Freeze4
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_wl_www_RapidDocument
 * Method:    _Freeze8
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_com_wl_www_RapidDocument__1Freeze8
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_wl_www_RapidDocument
 * Method:    _Render
 * Signature: (JJ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_wl_www_RapidDocument__1Render
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_wl_www_RapidDocument
 * Method:    _GetAllocator
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_wl_www_RapidDocument__1GetAllocator
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_wl_www_RapidDocument
 * Method:    _IsNull
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_com_wl_www_RapidDocument__1IsNull
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_wl_www_RapidDocument
 * Method:    _IsFalse
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_com_wl_www_RapidDocument__1IsFalse
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_wl_www_RapidDocument
 * Method:    _IsTrue
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_com_wl_www_RapidDocument__1IsTrue
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_wl_www_RapidDocument
 * Method:    _IsInt
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_com_wl_www_RapidDocument__1IsInt
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_wl_www_RapidDocument
 * Method:    _IsUint
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_com_wl_www_RapidDocument__1IsUint
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_wl_www_RapidDocument
 * Method:    _IsDouble
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_com_wl_www_RapidDocument__1IsDouble
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_wl_www_RapidDocument
 * Method:    _IsString
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_com_wl_www_RapidDocument__1IsString
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_wl_www_RapidDocument
 * Method:    _IsArray
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_com_wl_www_RapidDocument__1IsArray
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_wl_www_RapidDocument
 * Method:    _IsObject
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_com_wl_www_RapidDocument__1IsObject
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_wl_www_RapidDocument
 * Method:    _GetInt
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_com_wl_www_RapidDocument__1GetInt
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_wl_www_RapidDocument
 * Method:    _GetUint
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_com_wl_www_RapidDocument__1GetUint
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_wl_www_RapidDocument
 * Method:    _GetDouble
 * Signature: (JJ)D
 */
JNIEXPORT jdouble JNICALL Java_com_wl_www_RapidDocument__1GetDouble
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_wl_www_RapidDocument
 * Method:    _GetString
 * Signature: (JJ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_wl_www_RapidDocument__1GetString
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_wl_www_RapidDocument
 * Method:    _GetArraySize
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_com_wl_www_RapidDocument__1GetArraySize
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_wl_www_RapidDocument
 * Method:    _GetArray
 * Signature: (JJJ)J
 */
JNIEXPORT jlong JNICALL Java_com_wl_www_RapidDocument__1GetArray
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     com_wl_www_RapidDocument
 * Method:    _GetObjectSize
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_com_wl_www_RapidDocument__1GetObjectSize
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_wl_www_RapidDocument
 * Method:    _GetObjectKey
 * Signature: (JJJ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_wl_www_RapidDocument__1GetObjectKey
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     com_wl_www_RapidDocument
 * Method:    _GetObject
 * Signature: (JJJ)J
 */
JNIEXPORT jlong JNICALL Java_com_wl_www_RapidDocument__1GetObject
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     com_wl_www_RapidDocument
 * Method:    _ObjectSearch
 * Signature: (JJLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_wl_www_RapidDocument__1ObjectSearch
  (JNIEnv *, jobject, jlong, jlong, jstring);

/*
 * Class:     com_wl_www_RapidDocument
 * Method:    _Locate
 * Signature: (JJLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_wl_www_RapidDocument__1Locate
  (JNIEnv *, jobject, jlong, jlong, jstring);

/*
 * Class:     com_wl_www_RapidDocument
 * Method:    _SetNull
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_wl_www_RapidDocument__1SetNull
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_wl_www_RapidDocument
 * Method:    _SetFalse
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_wl_www_RapidDocument__1SetFalse
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_wl_www_RapidDocument
 * Method:    _SetTrue
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_wl_www_RapidDocument__1SetTrue
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_wl_www_RapidDocument
 * Method:    _SetInt
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_com_wl_www_RapidDocument__1SetInt
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     com_wl_www_RapidDocument
 * Method:    _SetUint
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_com_wl_www_RapidDocument__1SetUint
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     com_wl_www_RapidDocument
 * Method:    _SetDouble
 * Signature: (JJD)V
 */
JNIEXPORT void JNICALL Java_com_wl_www_RapidDocument__1SetDouble
  (JNIEnv *, jobject, jlong, jlong, jdouble);

/*
 * Class:     com_wl_www_RapidDocument
 * Method:    _SetString
 * Signature: (JJLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_wl_www_RapidDocument__1SetString
  (JNIEnv *, jobject, jlong, jlong, jstring);

/*
 * Class:     com_wl_www_RapidDocument
 * Method:    _SetArray
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_wl_www_RapidDocument__1SetArray
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_wl_www_RapidDocument
 * Method:    _SetObject
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_wl_www_RapidDocument__1SetObject
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_wl_www_RapidDocument
 * Method:    _ArrayClean
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_wl_www_RapidDocument__1ArrayClean
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_wl_www_RapidDocument
 * Method:    _ArrayAppendNull
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_com_wl_www_RapidDocument__1ArrayAppendNull
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_wl_www_RapidDocument
 * Method:    _ArrayAppend
 * Signature: (JJZ)J
 */
JNIEXPORT jlong JNICALL Java_com_wl_www_RapidDocument__1ArrayAppend__JJZ
  (JNIEnv *, jobject, jlong, jlong, jboolean);

/*
 * Class:     com_wl_www_RapidDocument
 * Method:    _ArrayAppend
 * Signature: (JJJ)J
 */
JNIEXPORT jlong JNICALL Java_com_wl_www_RapidDocument__1ArrayAppend__JJJ
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     com_wl_www_RapidDocument
 * Method:    _ArrayAppend
 * Signature: (JJD)J
 */
JNIEXPORT jlong JNICALL Java_com_wl_www_RapidDocument__1ArrayAppend__JJD
  (JNIEnv *, jobject, jlong, jlong, jdouble);

/*
 * Class:     com_wl_www_RapidDocument
 * Method:    _ArrayAppend
 * Signature: (JJLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_wl_www_RapidDocument__1ArrayAppend__JJLjava_lang_String_2
  (JNIEnv *, jobject, jlong, jlong, jstring);

/*
 * Class:     com_wl_www_RapidDocument
 * Method:    _ArrayAppendArray
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_com_wl_www_RapidDocument__1ArrayAppendArray
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_wl_www_RapidDocument
 * Method:    _ArrayAppendObject
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_com_wl_www_RapidDocument__1ArrayAppendObject
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_wl_www_RapidDocument
 * Method:    _ArrayRemove
 * Signature: (JJJ)J
 */
JNIEXPORT jlong JNICALL Java_com_wl_www_RapidDocument__1ArrayRemove
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     com_wl_www_RapidDocument
 * Method:    _ObjectClean
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_wl_www_RapidDocument__1ObjectClean
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_wl_www_RapidDocument
 * Method:    _ObjectAddNull
 * Signature: (JJLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_wl_www_RapidDocument__1ObjectAddNull
  (JNIEnv *, jobject, jlong, jlong, jstring);

/*
 * Class:     com_wl_www_RapidDocument
 * Method:    _ObjectAdd
 * Signature: (JJLjava/lang/String;Z)J
 */
JNIEXPORT jlong JNICALL Java_com_wl_www_RapidDocument__1ObjectAdd__JJLjava_lang_String_2Z
  (JNIEnv *, jobject, jlong, jlong, jstring, jboolean);

/*
 * Class:     com_wl_www_RapidDocument
 * Method:    _ObjectAdd
 * Signature: (JJLjava/lang/String;J)J
 */
JNIEXPORT jlong JNICALL Java_com_wl_www_RapidDocument__1ObjectAdd__JJLjava_lang_String_2J
  (JNIEnv *, jobject, jlong, jlong, jstring, jlong);

/*
 * Class:     com_wl_www_RapidDocument
 * Method:    _ObjectAdd
 * Signature: (JJLjava/lang/String;D)J
 */
JNIEXPORT jlong JNICALL Java_com_wl_www_RapidDocument__1ObjectAdd__JJLjava_lang_String_2D
  (JNIEnv *, jobject, jlong, jlong, jstring, jdouble);

/*
 * Class:     com_wl_www_RapidDocument
 * Method:    _ObjectAdd
 * Signature: (JJLjava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_wl_www_RapidDocument__1ObjectAdd__JJLjava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jobject, jlong, jlong, jstring, jstring);

/*
 * Class:     com_wl_www_RapidDocument
 * Method:    _ObjectAddArray
 * Signature: (JJLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_wl_www_RapidDocument__1ObjectAddArray
  (JNIEnv *, jobject, jlong, jlong, jstring);

/*
 * Class:     com_wl_www_RapidDocument
 * Method:    _ObjectAddObject
 * Signature: (JJLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_wl_www_RapidDocument__1ObjectAddObject
  (JNIEnv *, jobject, jlong, jlong, jstring);

/*
 * Class:     com_wl_www_RapidDocument
 * Method:    _ObjectRemove
 * Signature: (JJLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_wl_www_RapidDocument__1ObjectRemove
  (JNIEnv *, jobject, jlong, jlong, jstring);

#ifdef __cplusplus
}
#endif
#endif
