/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wl_www_FreezeDocument */

#ifndef _Included_com_wl_www_FreezeDocument
#define _Included_com_wl_www_FreezeDocument
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wl_www_FreezeDocument
 * Method:    BodySize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wl_www_FreezeDocument_BodySize
  (JNIEnv *, jobject);

/*
 * Class:     com_wl_www_FreezeDocument
 * Method:    IsNull
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_wl_www_FreezeDocument_IsNull
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_wl_www_FreezeDocument
 * Method:    IsFalse
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_wl_www_FreezeDocument_IsFalse
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_wl_www_FreezeDocument
 * Method:    IsTrue
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_wl_www_FreezeDocument_IsTrue
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_wl_www_FreezeDocument
 * Method:    IsInt
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_wl_www_FreezeDocument_IsInt
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_wl_www_FreezeDocument
 * Method:    IsUint
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_wl_www_FreezeDocument_IsUint
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_wl_www_FreezeDocument
 * Method:    IsDouble
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_wl_www_FreezeDocument_IsDouble
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_wl_www_FreezeDocument
 * Method:    IsString
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_wl_www_FreezeDocument_IsString
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_wl_www_FreezeDocument
 * Method:    IsArray
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_wl_www_FreezeDocument_IsArray
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_wl_www_FreezeDocument
 * Method:    IsObject
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_wl_www_FreezeDocument_IsObject
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_wl_www_FreezeDocument
 * Method:    GetType
 * Signature: (I)C
 */
JNIEXPORT jchar JNICALL Java_com_wl_www_FreezeDocument_GetType
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_wl_www_FreezeDocument
 * Method:    GetInt
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_com_wl_www_FreezeDocument_GetInt
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_wl_www_FreezeDocument
 * Method:    GetUint
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_com_wl_www_FreezeDocument_GetUint
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_wl_www_FreezeDocument
 * Method:    GetDouble
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_com_wl_www_FreezeDocument_GetDouble
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_wl_www_FreezeDocument
 * Method:    GetString
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_wl_www_FreezeDocument_GetString
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_wl_www_FreezeDocument
 * Method:    GetArraySize
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_wl_www_FreezeDocument_GetArraySize
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_wl_www_FreezeDocument
 * Method:    GetArray
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_wl_www_FreezeDocument_GetArray
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_wl_www_FreezeDocument
 * Method:    GetObjectSize
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_wl_www_FreezeDocument_GetObjectSize
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_wl_www_FreezeDocument
 * Method:    GetObjectKey
 * Signature: (II)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_wl_www_FreezeDocument_GetObjectKey
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_wl_www_FreezeDocument
 * Method:    GetObject
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_wl_www_FreezeDocument_GetObject
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_wl_www_FreezeDocument
 * Method:    SearchObject
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_wl_www_FreezeDocument_SearchObject
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     com_wl_www_FreezeDocument
 * Method:    Locate
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_wl_www_FreezeDocument_Locate
  (JNIEnv *, jobject, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
