/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wl_www_FreezeJson8Refer */

#ifndef _Included_com_wl_www_FreezeJson8Refer
#define _Included_com_wl_www_FreezeJson8Refer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wl_www_FreezeJson8Refer
 * Method:    _IsNull
 * Signature: (Lcom/wl/www/FreezeJson8Holder;I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_wl_www_FreezeJson8Refer__1IsNull
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     com_wl_www_FreezeJson8Refer
 * Method:    _IsFalse
 * Signature: (Lcom/wl/www/FreezeJson8Holder;I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_wl_www_FreezeJson8Refer__1IsFalse
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     com_wl_www_FreezeJson8Refer
 * Method:    _IsTrue
 * Signature: (Lcom/wl/www/FreezeJson8Holder;I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_wl_www_FreezeJson8Refer__1IsTrue
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     com_wl_www_FreezeJson8Refer
 * Method:    _IsInt
 * Signature: (Lcom/wl/www/FreezeJson8Holder;I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_wl_www_FreezeJson8Refer__1IsInt
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     com_wl_www_FreezeJson8Refer
 * Method:    _IsUint
 * Signature: (Lcom/wl/www/FreezeJson8Holder;I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_wl_www_FreezeJson8Refer__1IsUint
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     com_wl_www_FreezeJson8Refer
 * Method:    _IsDouble
 * Signature: (Lcom/wl/www/FreezeJson8Holder;I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_wl_www_FreezeJson8Refer__1IsDouble
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     com_wl_www_FreezeJson8Refer
 * Method:    _IsString
 * Signature: (Lcom/wl/www/FreezeJson8Holder;I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_wl_www_FreezeJson8Refer__1IsString
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     com_wl_www_FreezeJson8Refer
 * Method:    _IsArray
 * Signature: (Lcom/wl/www/FreezeJson8Holder;I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_wl_www_FreezeJson8Refer__1IsArray
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     com_wl_www_FreezeJson8Refer
 * Method:    _IsObject
 * Signature: (Lcom/wl/www/FreezeJson8Holder;I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_wl_www_FreezeJson8Refer__1IsObject
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     com_wl_www_FreezeJson8Refer
 * Method:    _GetType
 * Signature: (Lcom/wl/www/FreezeJson8Holder;I)C
 */
JNIEXPORT jchar JNICALL Java_com_wl_www_FreezeJson8Refer__1GetType
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     com_wl_www_FreezeJson8Refer
 * Method:    _GetInt
 * Signature: (Lcom/wl/www/FreezeJson8Holder;I)J
 */
JNIEXPORT jlong JNICALL Java_com_wl_www_FreezeJson8Refer__1GetInt
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     com_wl_www_FreezeJson8Refer
 * Method:    _GetUint
 * Signature: (Lcom/wl/www/FreezeJson8Holder;I)J
 */
JNIEXPORT jlong JNICALL Java_com_wl_www_FreezeJson8Refer__1GetUint
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     com_wl_www_FreezeJson8Refer
 * Method:    _GetDouble
 * Signature: (Lcom/wl/www/FreezeJson8Holder;I)D
 */
JNIEXPORT jdouble JNICALL Java_com_wl_www_FreezeJson8Refer__1GetDouble
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     com_wl_www_FreezeJson8Refer
 * Method:    _GetString
 * Signature: (Lcom/wl/www/FreezeJson8Holder;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_wl_www_FreezeJson8Refer__1GetString
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     com_wl_www_FreezeJson8Refer
 * Method:    _GetArraySize
 * Signature: (Lcom/wl/www/FreezeJson8Holder;I)I
 */
JNIEXPORT jint JNICALL Java_com_wl_www_FreezeJson8Refer__1GetArraySize
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     com_wl_www_FreezeJson8Refer
 * Method:    _GetArray
 * Signature: (Lcom/wl/www/FreezeJson8Holder;II)I
 */
JNIEXPORT jint JNICALL Java_com_wl_www_FreezeJson8Refer__1GetArray
  (JNIEnv *, jobject, jobject, jint, jint);

/*
 * Class:     com_wl_www_FreezeJson8Refer
 * Method:    _GetObjectSize
 * Signature: (Lcom/wl/www/FreezeJson8Holder;I)I
 */
JNIEXPORT jint JNICALL Java_com_wl_www_FreezeJson8Refer__1GetObjectSize
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     com_wl_www_FreezeJson8Refer
 * Method:    _GetObjectKey
 * Signature: (Lcom/wl/www/FreezeJson8Holder;II)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_wl_www_FreezeJson8Refer__1GetObjectKey
  (JNIEnv *, jobject, jobject, jint, jint);

/*
 * Class:     com_wl_www_FreezeJson8Refer
 * Method:    _GetObject
 * Signature: (Lcom/wl/www/FreezeJson8Holder;II)I
 */
JNIEXPORT jint JNICALL Java_com_wl_www_FreezeJson8Refer__1GetObject
  (JNIEnv *, jobject, jobject, jint, jint);

/*
 * Class:     com_wl_www_FreezeJson8Refer
 * Method:    _SearchObject
 * Signature: (Lcom/wl/www/FreezeJson8Holder;ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_wl_www_FreezeJson8Refer__1SearchObject
  (JNIEnv *, jobject, jobject, jint, jstring);

/*
 * Class:     com_wl_www_FreezeJson8Refer
 * Method:    _Locate
 * Signature: (Lcom/wl/www/FreezeJson8Holder;ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_wl_www_FreezeJson8Refer__1Locate
  (JNIEnv *, jobject, jobject, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
