/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wl_www_FreezeJson4Holder */

#ifndef _Included_com_wl_www_FreezeJson4Holder
#define _Included_com_wl_www_FreezeJson4Holder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wl_www_FreezeJson4Holder
 * Method:    _Init
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_wl_www_FreezeJson4Holder__1Init__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_wl_www_FreezeJson4Holder
 * Method:    _Init
 * Signature: (Lcom/wl/www/FreezeJson4Holder;I)J
 */
JNIEXPORT jlong JNICALL Java_com_wl_www_FreezeJson4Holder__1Init__Lcom_wl_www_FreezeJson4Holder_2I
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     com_wl_www_FreezeJson4Holder
 * Method:    _Free
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_wl_www_FreezeJson4Holder__1Free
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_wl_www_FreezeJson4Holder
 * Method:    _writeObject
 * Signature: (JLjava/io/ObjectOutputStream;)V
 */
JNIEXPORT void JNICALL Java_com_wl_www_FreezeJson4Holder__1writeObject
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     com_wl_www_FreezeJson4Holder
 * Method:    _readObject
 * Signature: (JLjava/io/ObjectInputStream;)V
 */
JNIEXPORT void JNICALL Java_com_wl_www_FreezeJson4Holder__1readObject
  (JNIEnv *, jobject, jlong, jobject);

#ifdef __cplusplus
}
#endif
#endif
