/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wl_www_FreezeDocument8 */

#ifndef _Included_com_wl_www_FreezeDocument8
#define _Included_com_wl_www_FreezeDocument8
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wl_www_FreezeDocument8
 * Method:    _Init
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_wl_www_FreezeDocument8__1Init__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_wl_www_FreezeDocument8
 * Method:    _Init
 * Signature: (Lcom/wl/www/FreezeDocument8;J)J
 */
JNIEXPORT jlong JNICALL Java_com_wl_www_FreezeDocument8__1Init__Lcom_wl_www_FreezeDocument8_2J
  (JNIEnv *, jobject, jobject, jlong);

/*
 * Class:     com_wl_www_FreezeDocument8
 * Method:    _Free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_wl_www_FreezeDocument8__1Free
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_wl_www_FreezeDocument8
 * Method:    _writeObject
 * Signature: (JLjava/io/ObjectOutputStream;)V
 */
JNIEXPORT void JNICALL Java_com_wl_www_FreezeDocument8__1writeObject
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     com_wl_www_FreezeDocument8
 * Method:    _readObject
 * Signature: (Ljava/io/ObjectInputStream;)J
 */
JNIEXPORT jlong JNICALL Java_com_wl_www_FreezeDocument8__1readObject
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wl_www_FreezeDocument8
 * Method:    _BodySize
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_wl_www_FreezeDocument8__1BodySize
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_wl_www_FreezeDocument8
 * Method:    _Unfreeze
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_com_wl_www_FreezeDocument8__1Unfreeze
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_wl_www_FreezeDocument8
 * Method:    _Render
 * Signature: (JJ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_wl_www_FreezeDocument8__1Render
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_wl_www_FreezeDocument8
 * Method:    _IsRemoved
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_com_wl_www_FreezeDocument8__1IsRemoved
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_wl_www_FreezeDocument8
 * Method:    _IsNull
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_com_wl_www_FreezeDocument8__1IsNull
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_wl_www_FreezeDocument8
 * Method:    _IsFalse
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_com_wl_www_FreezeDocument8__1IsFalse
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_wl_www_FreezeDocument8
 * Method:    _IsTrue
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_com_wl_www_FreezeDocument8__1IsTrue
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_wl_www_FreezeDocument8
 * Method:    _IsInt
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_com_wl_www_FreezeDocument8__1IsInt
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_wl_www_FreezeDocument8
 * Method:    _IsUint
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_com_wl_www_FreezeDocument8__1IsUint
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_wl_www_FreezeDocument8
 * Method:    _IsDouble
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_com_wl_www_FreezeDocument8__1IsDouble
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_wl_www_FreezeDocument8
 * Method:    _IsString
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_com_wl_www_FreezeDocument8__1IsString
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_wl_www_FreezeDocument8
 * Method:    _IsArray
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_com_wl_www_FreezeDocument8__1IsArray
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_wl_www_FreezeDocument8
 * Method:    _IsObject
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_com_wl_www_FreezeDocument8__1IsObject
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_wl_www_FreezeDocument8
 * Method:    _GetInt
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_com_wl_www_FreezeDocument8__1GetInt
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_wl_www_FreezeDocument8
 * Method:    _GetUint
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_com_wl_www_FreezeDocument8__1GetUint
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_wl_www_FreezeDocument8
 * Method:    _GetDouble
 * Signature: (JJ)D
 */
JNIEXPORT jdouble JNICALL Java_com_wl_www_FreezeDocument8__1GetDouble
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_wl_www_FreezeDocument8
 * Method:    _GetString
 * Signature: (JJ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_wl_www_FreezeDocument8__1GetString
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_wl_www_FreezeDocument8
 * Method:    _GetArraySpace
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_com_wl_www_FreezeDocument8__1GetArraySpace
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_wl_www_FreezeDocument8
 * Method:    _GetArraySize
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_com_wl_www_FreezeDocument8__1GetArraySize
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_wl_www_FreezeDocument8
 * Method:    _GetArray
 * Signature: (JJJ)J
 */
JNIEXPORT jlong JNICALL Java_com_wl_www_FreezeDocument8__1GetArray
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     com_wl_www_FreezeDocument8
 * Method:    _GetObjectSpace
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_com_wl_www_FreezeDocument8__1GetObjectSpace
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_wl_www_FreezeDocument8
 * Method:    _GetObjectSize
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_com_wl_www_FreezeDocument8__1GetObjectSize
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_wl_www_FreezeDocument8
 * Method:    _GetObjectKey
 * Signature: (JJJ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_wl_www_FreezeDocument8__1GetObjectKey
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     com_wl_www_FreezeDocument8
 * Method:    _GetObject
 * Signature: (JJJ)J
 */
JNIEXPORT jlong JNICALL Java_com_wl_www_FreezeDocument8__1GetObject
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     com_wl_www_FreezeDocument8
 * Method:    _ObjectSearch
 * Signature: (JJLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_wl_www_FreezeDocument8__1ObjectSearch
  (JNIEnv *, jobject, jlong, jlong, jstring);

/*
 * Class:     com_wl_www_FreezeDocument8
 * Method:    _Locate
 * Signature: (JJLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_wl_www_FreezeDocument8__1Locate
  (JNIEnv *, jobject, jlong, jlong, jstring);

/*
 * Class:     com_wl_www_FreezeDocument8
 * Method:    _Remove
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_wl_www_FreezeDocument8__1Remove
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_wl_www_FreezeDocument8
 * Method:    _SetNull
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_wl_www_FreezeDocument8__1SetNull
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_wl_www_FreezeDocument8
 * Method:    _SetFalse
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_wl_www_FreezeDocument8__1SetFalse
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_wl_www_FreezeDocument8
 * Method:    _SetTrue
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_wl_www_FreezeDocument8__1SetTrue
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_wl_www_FreezeDocument8
 * Method:    _SetInt
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_com_wl_www_FreezeDocument8__1SetInt
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     com_wl_www_FreezeDocument8
 * Method:    _SetUint
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_com_wl_www_FreezeDocument8__1SetUint
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     com_wl_www_FreezeDocument8
 * Method:    _SetDouble
 * Signature: (JJD)V
 */
JNIEXPORT void JNICALL Java_com_wl_www_FreezeDocument8__1SetDouble
  (JNIEnv *, jobject, jlong, jlong, jdouble);

#ifdef __cplusplus
}
#endif
#endif
