# -*- python -*-

env = Environment(CCFLAGS = ['-g', '-Wall', '-m64'],
                  PROGSUFFIX = '.exe')
qtenv = env.Clone(tools = ['default', 'qt'],
                  CPPDEFINES = ['_REENTRANT',
                                'QT_NO_DEBUG',
                                'QT_CORE_LIB'],
                  QTDIR = '/usr',
                  QT_LIB = None)
qtenv.ParseConfig('pkg-config --cflags --libs QtCore')

qtenv.Program('testqdir', ['testqdir.cpp'])

qtenv0 = qtenv.Clone()
qtenv0.Append(CPPDEFINES = 'QT_GUI_LIB')
qtenv0.ParseConfig('pkg-config --cflags --libs QtGui')

qtenv0.Program('addressbook', ['main.cpp', 'addressbook.cpp'])
