# -*- python -*-

env = Environment(CCFLAGS = ['-g', '-Wall', '-m64'],
                  PROGSUFFIX = '.exe')
qtenv = env.Clone(tools = ['default', 'qt'],
                  CPPDEFINES = ['_REENTRANT',
                                'QT_NO_DEBUG',
                                'QT_GUI_LIB',
                                'QT_CORE_LIB'],
                  QTDIR = '/usr',
                  QT_LIB = None)
qtenv.ParseConfig('pkg-config --cflags --libs QtGui QtCore')

#qtenv.Program('addressbook', 'addressbook.cpp')
qtenv.Program('addressbook', ['main.cpp', 'addressbook.cpp'])
