# -*- python -*-

env = Environment(CCFLAGS = ['-g', '-Wall'],
                  SWIGFLAGS = ['-python'],
                  SHLIBPREFIX = '_')
env.ParseConfig('python-config --includes --libs')

cppenv = env.Clone()
cppenv.Append(SWIGFLAGS = ['-c++'])

env.SharedLibrary('cexample', ['cexample.i', 'cexample.c'])
cppenv.SharedLibrary('example', ['example.i', 'example.cxx'])
cppenv.SharedLibrary('clsexample', ['clsexample.i', 'clsexample.cpp'])
