# -*- python -*-

env = Environment(CCFLAGS = ['-g', '-Wall'],
                  PROGSUFFIX = '.exe')
env.Program('sizeof', 'sizeof.c')
env.Program('printf', 'printf.c')
env.Program('cdouble', 'cdouble.c')
env.Program('rlimit', 'rlimit.c')
env.Program('try_waitpid', 'try_waitpid.c')
