# -*- python -*-

env = Environment(CCFLAGS = ['-g', '-Wall'],
                  CPPDEFINES = ['HAVE_HIDDEN',
                                ('_LARGEFILE64_SOURCE', 1)],
                  PROGSUFFIX = '.exe')
env.Program('gzop', ['main.c', 'gzlib.c'], LIBS = ['z'])

