# -*- python -*-
import glob, os.path

env = Environment(JAVACLASSPATH = '/usr/share/java/json-lib.jar',
                  CPPPATH = ['/usr/lib/jvm/java-8-openjdk-amd64/include',
                             '/usr/lib/jvm/java-8-openjdk-amd64/include/linux'],
                  PROGSUFFIX = '.exe')

dn = os.path.join('com', 'wl', 'www')
env.Java(target = 'classes', source = 'sources')
env.JavaH(target = 'jni', source =
          map(lambda classname: os.path.join('classes', 'com', 'wl', 'www', classname),
              ['FreezeJson4', 'FreezeJson8']))
env.SharedLibrary(os.path.join('jni', 'freeze'), os.path.join('jni', 'freeze-jni.cpp'))
env.Program(os.path.join('jni', 'tstfreeze0'), [os.path.join('jni', 'tstfreeze0.cpp')])
env.Program(os.path.join('jni', 'tstfreeze1'), [os.path.join('jni', 'tstfreeze1.cpp')])
env.Program(os.path.join('jni', 'tstfreeze2'), [os.path.join('jni', 'tstfreeze2.cpp')])
