# -*- python -*-
from glob import glob
from os.path import join as pathjoin, splitext

env = Environment(CXXFLAGS = ['-g', '-O', '-Wall'],
                  CPPPATH = ['srcs'],
                  PROGSUFFIX = '.exe')

libobj = env.Library(pathjoin('srcs', 'flatten'), glob(pathjoin('srcs', '*.cpp')))
for tstfpath in glob(pathjoin('tests', '*.cpp')):
    env.Program(splitext(tstfpath), [tstfpath] + libobj)
