# -*- python -*-

env = Environment(CCFLAGS = ['-g', '-Wall'],
                  PROGSUFFIX = '.exe', LIBS = ['bz2'])
env.ParseConfig('pkg-config --cflags --libs openssl')

env.Program('bftest0', ['bftest0.cpp', 'bookfile.cpp'])
env.Program('bftest1', ['bftest1.cpp', 'bookfile.cpp'])
env.Program('bftest2', ['bftest2.cpp', 'bookfile.cpp'])

pyenv = env.Clone()
pyenv['SHLIBPREFIX'] = ''
pyenv.ParseConfig('python-config --cflags --libs')
pyenv.SharedLibrary('bookfile', ['pybookfile.cpp', 'bookfile.cpp', 'accessor.cpp'])
