# -*- python -*-
from glob import glob
from os.path import join as pathjoin

if ARGUMENTS.get('debug', 0): ccflags = ['-g', '-Wall', '-std=c99']
else: ccflags = ['-O3', '-Wall', '-flto', '-Ofast', '-fomit-frame-pointer', '-std=c99']
env = Environment(CCFLAGS = ccflags,
                  CPPPATH = ['.'],
                  PROGSUFFIX = '.exe')

objs = map(lambda src: env.Object(src)[0],
           glob(pathjoin('density', '*.c')) + glob(pathjoin('spookyhash', '*.c')))
env.Program('sharc', glob(pathjoin('sharc', '*.c')) + objs)
env.Program('first', ['first.c'] + objs)
