# -*- python -*-
from glob import glob
from os.path import join as pathjoin

env = Environment(CCFLAGS = ['-g', '-Wall', '-flto', '-Ofast',
                             '-fomit-frame-pointer', '-std=c++11'],
                  CPPDEFINES = [('_FILE_OFFSET_BITS', 64)],
                  CPPPATH = ['.'],
                  PROGSUFFIX = '.exe')

objs = map(lambda src: env.Object(src)[0], glob(pathjoin('densityxx', '*.cpp')))
